package MoreFences.ClexaGod.morefences;

import java.util.List;

public final class FenceDefinitions {
    private FenceDefinitions() {}
    public record FenceDefinition(String path, String textureKey) {
        public String displayNameKey(String namespace) {
            return "tile." + namespace + ":" + path + ".name";
        }
    }
    public static final List<FenceDefinition> ALL = List.of(
        new FenceDefinition("amethyst_fence", "flappyguy_amethyst_fence"),
        new FenceDefinition("basalt_fence", "smooth_basalt"),
        new FenceDefinition("bedrock_fence", "flappyguy_bedrock_fence"),
        new FenceDefinition("black_concrete", "concrete_black"),
        new FenceDefinition("black_wool", "wool_colored_black"),
        new FenceDefinition("blackstone_fence", "flappyguy_blackstone_fence"),
        new FenceDefinition("blue_concrete", "concrete_blue"),
        new FenceDefinition("blue_wool", "wool_colored_blue"),
        new FenceDefinition("brick_fence", "flappyguy_brick_fence"),
        new FenceDefinition("brown_concrete", "concrete_brown"),
        new FenceDefinition("brown_wool", "wool_colored_brown"),
        new FenceDefinition("calcite_fence", "calcite"),
        new FenceDefinition("coal_fence", "flappyguy_coal_fence"),
        new FenceDefinition("cobbled_deepslate_fence", "cobbled_deepslate"),
        new FenceDefinition("cobblestone_fence", "flappyguy_cobblestone_fence"),
        new FenceDefinition("crying_obsidian_fence", "flappyguy_crying_obsidian_fence"),
        new FenceDefinition("cyan_concrete", "concrete_cyan"),
        new FenceDefinition("cyan_wool", "wool_colored_cyan"),
        new FenceDefinition("diamond_fence", "flappyguy_diamond_fence"),
        new FenceDefinition("dirt_fence", "flappyguy_dirt_fence"),
        new FenceDefinition("dripstone_fence", "flappyguy_dripstone_fence"),
        new FenceDefinition("emerald_fence", "flappyguy_emerald_fence"),
        new FenceDefinition("endstone_fence", "flappyguy_endstone_fence"),
        new FenceDefinition("glowstone_fence", "flappyguy_glowstone_fence"),
        new FenceDefinition("gold_fence", "flappyguy_gold_fence"),
        new FenceDefinition("granite_fence", "stone_granite_smooth"),
        new FenceDefinition("gray_concrete", "concrete_gray"),
        new FenceDefinition("gray_wool", "wool_colored_gray"),
        new FenceDefinition("green_bamboo_fence", "flappyguy_green_bamboo_fence"),
        new FenceDefinition("green_concrete", "concrete_green"),
        new FenceDefinition("green_wool", "wool_colored_green"),
        new FenceDefinition("hay_fence", "flappyguy_hay_fence"),
        new FenceDefinition("honeycomb_fence", "flappyguy_coal_fence"),
        new FenceDefinition("ice_fence", "flappyguy_ice_fence"),
        new FenceDefinition("iron_fence", "flappyguy_iron_fence"),
        new FenceDefinition("lapis_lazuli_fenceby78", "flappyguy_lapis_lazuli_fenceby78"),
        new FenceDefinition("light_blue_concrete", "concrete_light_blue"),
        new FenceDefinition("light_blue_wool", "wool_colored_light_blue"),
        new FenceDefinition("light_gray_concrete", "concrete_light_gray"),
        new FenceDefinition("light_gray_wool", "wool_colored_light_gray"),
        new FenceDefinition("lime_concrete", "concrete_lime"),
        new FenceDefinition("lime_wool", "wool_colored_lime"),
        new FenceDefinition("magenta_concrete", "concrete_magenta"),
        new FenceDefinition("magenta_wool", "wool_colored_magenta"),
        new FenceDefinition("moss_fence", "flappyguy_moss_fence"),
        new FenceDefinition("mud_fence", "flappyguy_mud_fence"),
        new FenceDefinition("muddy_fence", "mud"),
        new FenceDefinition("netherite_fence", "flappyguy_netherite_fence"),
        new FenceDefinition("netherrack_fence", "flappyguy_netherrack_fence"),
        new FenceDefinition("obsidian_fence", "flappyguy_obsidian_fence"),
        new FenceDefinition("ochre_froglight_fence", "flappyguy_ochre_froglight_fence"),
        new FenceDefinition("orange_concrete", "concrete_orange"),
        new FenceDefinition("orange_wool", "wool_colored_orange"),
        new FenceDefinition("pearlescent_froglight_fence", "flappyguy_pearlescent_froglight_fence"),
        new FenceDefinition("pink_concrete", "concrete_pink"),
        new FenceDefinition("pink_wool", "wool_colored_pink"),
        new FenceDefinition("prismarine_fence", "flappyguy_prismarine_fence"),
        new FenceDefinition("purple_concrete", "concrete_purple"),
        new FenceDefinition("purple_wool", "wool_colored_purple"),
        new FenceDefinition("purpur_fence", "flappyguy_purpur_fence"),
        new FenceDefinition("quartz_fence", "flappyguy_quartz_fence"),
        new FenceDefinition("raw_copper_block_fence", "raw_copper_block"),
        new FenceDefinition("raw_gold_block_fence", "raw_gold_block"),
        new FenceDefinition("raw_iron_block_fence", "raw_iron_block"),
        new FenceDefinition("red_concrete", "concrete_red"),
        new FenceDefinition("red_wool", "wool_colored_red"),
        new FenceDefinition("resin_fence", "flappyguy_resin_fence"),
        new FenceDefinition("sandstone_fence", "flappyguy_sandstone_fence"),
        new FenceDefinition("sculk_fence", "sculk_sensor_bottom.png"),
        new FenceDefinition("shroomlight_fence", "flappyguy_shroomlight_fence"),
        new FenceDefinition("snow_fence", "flappyguy_snow_fence"),
        new FenceDefinition("soul_soil_fence", "flappyguy_soul_soil_fence"),
        new FenceDefinition("stonebrick_fence", "flappyguy_stonebrick_fence"),
        new FenceDefinition("tuff_fence", "flappyguy_tuff_fence"),
        new FenceDefinition("verdant_froglight_fence", "flappyguy_verdant_froglight_fence"),
        new FenceDefinition("white_concrete", "concrete_white"),
        new FenceDefinition("white_wool", "wool_colored_white"),
        new FenceDefinition("yellow_concrete", "concrete_yellow"),
        new FenceDefinition("yellow_wool", "wool_colored_yellow")
    );
}
